---

#- name: Create tenant
#  cisco.aci.aci_tenant:
#    host: "{{ansible_host}}"
#    username: "{{username}}"
#    password: "{{password}}"
#    tenant: "{{tenant_name}}"
#    description: "{{tenant_description}}"
#    state: present


- name: Query all contracts
  cisco.aci.aci_contract:
    host: "{{ansible_host}}"
    username: "{{username}}"
    password: "{{password}}"
    tenant: SnV
    state: query
  delegate_to: localhost
  register: query_result
  

- name: Filter Output
  debug:
    msg: "{{ query_result | community.general.json_query('current[*].fvTenant.children[*].vzBrCP.attributes.name') }}"


  